#!/usr/bin/env python3
"""enot build engine: render every port under ports/ from colors.json.

One spec (colors.json) drives all ports. A port is a directory under
ports/ with a port.json manifest of one of three kinds:

- template: a ${var}-placeholder file rendered per output theme via
  string.Template; no Python -- this is the path for the long tail of
  simple key=value color formats;
- module: a render.py exposing render(spec) -> {path: text}, for
  formats whose emission needs logic (vim attributes, mc inheritance);
- static: a source file copied verbatim (ranger's imperative scheme).

Outputs land at the paths declared in each manifest -- the install
locations -- and this file adds no color math. It also writes
ports/registry.json, the coverage manifest the site builds its port
matrix from.
"""

import importlib.util
import json
import os
from string import Template

from palette import ANSI_ORDER, SLUG

AUTHOR = "generated by the enot build (CIELAB, CVD-hardened)"
PORTS_DIR = "ports"
REGISTRY_FIELDS = ("app", "name", "category", "kind", "depth",
                   "guarantee", "outputs")


def toml_list(values):
    return "[" + ", ".join(f'"{v}"' for v in values) + "]"


def namespace(theme_name, theme):
    """Flat ${var} namespace for a template port, scoped to one theme."""
    ns = {"slug": SLUG, "theme": theme_name,
          "scheme_name": f"{SLUG}-{theme_name}", "author": AUTHOR}
    for role, e in theme["roles"].items():
        ns[role] = e["hex"]
        ns[f"{role}_c256"] = str(e["c256"])
        ns[f"{role}_c256hex"] = e["c256hex"]
    a = {k: e["hex"] for k, e in theme["ansi"].items()}
    ns["ansi"] = toml_list(a[n] for n in ANSI_ORDER)
    ns["brights"] = toml_list(a["br_" + n] for n in ANSI_ORDER)
    for k, e in theme["ansi"].items():
        ns[f"ansi_{k}"] = e["hex"]
    return ns


def render_template(port_dir, manifest, spec):
    tmpl = Template(open(os.path.join(port_dir, manifest["template"])).read())
    out = {}
    for o in manifest["outputs"]:
        ns = namespace(o["theme"], spec["themes"][o["theme"]])
        out[o["path"]] = tmpl.substitute(ns)
    return out


def render_module(port_dir, manifest, spec):
    path = os.path.join(port_dir, manifest["module"])
    mspec = importlib.util.spec_from_file_location("_enot_port", path)
    mod = importlib.util.module_from_spec(mspec)
    mspec.loader.exec_module(mod)
    return mod.render(spec)


def render_static(port_dir, manifest, spec):
    src = open(os.path.join(port_dir, manifest["src"])).read()
    return {manifest["outputs"][0]["path"]: src}


KINDS = {"template": render_template, "module": render_module,
         "static": render_static}


def main():
    with open("colors.json") as f:
        spec = json.load(f)
    registry = []
    for app in sorted(os.listdir(PORTS_DIR)):
        port_dir = os.path.join(PORTS_DIR, app)
        manifest_path = os.path.join(port_dir, "port.json")
        if not os.path.isfile(manifest_path):
            continue
        with open(manifest_path) as f:
            manifest = json.load(f)
        outputs = KINDS[manifest["kind"]](port_dir, manifest, spec)
        declared = {o["path"] for o in manifest["outputs"]}
        if set(outputs) != declared:
            raise SystemExit(f"{app}: rendered {sorted(outputs)} "
                             f"!= declared {sorted(declared)}")
        for path, text in outputs.items():
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as f:
                f.write(text)
            print(path)
        registry.append({k: manifest[k] for k in REGISTRY_FIELDS})
    with open(os.path.join(PORTS_DIR, "registry.json"), "w") as f:
        json.dump({"slug": SLUG, "ports": registry}, f, indent=2)
        f.write("\n")
    print(os.path.join(PORTS_DIR, "registry.json"))


if __name__ == "__main__":
    main()
