#!/usr/bin/env python3
"""WezTerm schemes from colors.json (enot variant).

Writes wezterm/enot-{dark,light}.toml: roles and ANSI 16 from the 16M
depth of the spec, no colors are computed here. Install: copy the files
into ~/.config/wezterm/colors/ and set color_scheme = "enot-dark".
"""

import json
import os

SLUG = "enot"
ANSI_ORDER = ["black", "red", "green", "yellow",
              "blue", "magenta", "cyan", "white"]


def toml_list(values):
    return "[" + ", ".join(f'"{v}"' for v in values) + "]"


def scheme(theme, name):
    t = {k: e["hex"] for k, e in theme["roles"].items()}
    a = {k: e["hex"] for k, e in theme["ansi"].items()}
    ansi = toml_list(a[n] for n in ANSI_ORDER)
    brights = toml_list(a["br_" + n] for n in ANSI_ORDER)
    return f"""[colors]
ansi = {ansi}
brights = {brights}
background = "{t['bg0']}"
foreground = "{t['fg0']}"
cursor_bg = "{t['fg0']}"
cursor_fg = "{t['bg0']}"
cursor_border = "{t['fg0']}"
selection_bg = "{t['bg2']}"
selection_fg = "{t['fg0']}"
split = "{t['bg3']}"
scrollbar_thumb = "{t['bg2']}"

[colors.tab_bar]
background = "{t['bg1']}"

[colors.tab_bar.active_tab]
bg_color = "{t['bg0']}"
fg_color = "{t['fg0']}"

[colors.tab_bar.inactive_tab]
bg_color = "{t['bg1']}"
fg_color = "{t['fg1']}"

[metadata]
name = "{name}"
author = "generated by wezterm.py (CIELAB, CVD-hardened)"
"""


def main():
    with open("colors.json") as f:
        spec = json.load(f)
    os.makedirs("wezterm", exist_ok=True)
    for mode in ("dark", "light"):
        path = f"wezterm/{SLUG}-{mode}.toml"
        with open(path, "w") as f:
            f.write(scheme(spec["themes"][mode], f"{SLUG}-{mode}"))
        print(path)


if __name__ == "__main__":
    main()
