#!/usr/bin/env python3
"""Site data bundle: the pipeline's contract with the Astro site.

All color math stays here. sitedata.py emits, into build/site/, the
machine-computed facts the site renders but must never recompute:

- vision: enot and gruvbox palettes run through the dichromacy
  simulations (cvd.SIM_FUNCS) for every theme and vision, so the live
  switcher on the site is a lookup, not a reimplementation of the
  matrices;
- metrics, gates, numbers: colors.json metrics, the check.py thresholds
  and the headline minima;
- ports: ports/registry.json passed through for the coverage matrix.

It also writes the download bundle (scheme files + colors.json) and the
llms.txt / llms-full.txt text deliverables. The site repo owns all
prose; this file owns all numbers. make deploy syncs build/site/ into
the Astro project and pushes it.
"""

import json
import math
import os
import shutil
import textwrap

from cvd import SIM_FUNCS
from palette import (ANSI_ORDER, GRUVBOX, NEUTRAL_ROLES, ROLES, SLUG,
                     enot_variant)

BASE_URL = "https://enot-theme.github.io/"
OUT = "build/site"
ROLE_KEYS = NEUTRAL_ROLES + ROLES


def vision_sets(colors):
    """vision name -> {key: hex} (or list) for a dict/list of colors."""
    def run(fn):
        if isinstance(colors, dict):
            return {k: fn(h) for k, h in colors.items()}
        return [fn(h) for h in colors]
    sets = {"normal": run(lambda h: h)}
    for name, fn in SIM_FUNCS.items():
        sets[name] = run(fn)
    return sets


def build_vision(variant):
    data = {"enot": {}, "gruvbox": {}}
    for mode in ("dark", "light"):
        theme = {k: variant[mode][k] for k in ROLE_KEYS}
        data["enot"][mode] = vision_sets(theme)
        data["gruvbox"][mode] = vision_sets(GRUVBOX[mode])
    return data


def floor1(x):
    """Floor to one decimal. A ">=" guarantee must never round up: the
    advertised minimum has to stay at or below the measured worst case
    (8.27 -> 8.2, never round(8.27, 1) = 8.3)."""
    return math.floor(x * 10 + 1e-9) / 10


def headline_numbers(spec):
    """Advertised min dE00 for the two truecolor invariants, floored over
    the worse of dark and light - the numbers behind the site's ">=" cards
    and the llms.txt summary."""
    def worst(metric):
        return floor1(min(spec["metrics"][m]["16M"][metric]
                          for m in ("dark", "light")))
    return worst("accents"), worst("ansi16")


def bundle(variant, spec, checks, ports):
    acc, ansi = headline_numbers(spec)
    return {
        "slug": SLUG,
        "accents": ROLES,
        "vision": build_vision(variant),
        "metrics": spec["metrics"],
        "gates": [{"mode": m, "depth": d, "metric": k, "threshold": t}
                  for m, d, k, t in checks],
        "numbers": {"accentsMin": acc, "ansiMin": ansi},
        "ports": ports["ports"],
    }


def and_join(names):
    return ", ".join(names[:-1]) + " and " + names[-1]


def llms_txt(acc, ansi, ports):
    """The app names, file lists and install links all derive from the
    port registry: a new port lands here without touching this file."""
    b = BASE_URL
    quote = textwrap.fill(
        f"An earthy color scheme for {and_join([p['name'] for p in ports])}: "
        f"dark and light themes, gruvbox character, built in CIELAB and "
        f"machine-checked to stay distinguishable under color blindness - "
        f"minimum pairwise CIEDE2000 of {acc} between syntax accents and "
        f"{ansi} across the 16 ANSI colors, verified against simulated "
        f"protanopia and deuteranopia.",
        width=70, initial_indent="> ", subsequent_indent="> ")
    # downloads are app-scoped ({app}/{file}): identical basenames across
    # ports (vim and lightline both ship enot.vim) must not collide
    files = "\n".join(
        f"- [{os.path.basename(o['path'])}]"
        f"({b}{p['app']}/{os.path.basename(o['path'])})"
        f": {p['name']}" + (f", {o['theme']} theme" if "theme" in o else "")
        for p in ports for o in p["outputs"])
    installs = "\n".join(
        f"- [Install for {p['name']}]({b}{p['app']}/)" for p in ports)
    return f"""# enot

{quote}

The name is the Russian word for raccoon; every color is generated by
an optimizer, none are hand-picked. Dichromacy is simulated with
Vienot 1999 and Brettel 1997 matrices in linear sRGB; a regression
gate fails the build if any guarantee drops.

## Scheme files

{files}
- [colors.json]({b}colors.json): the color spec - roles at three depths
  (true color, xterm-256, ANSI 16) with measured invariant metrics

## Documentation

{installs}
- [Applications and coverage]({b}apps/)
- [All install targets]({b}get/)
- [Why warm themes collapse under color blindness]({b}why/)
- [Measured guarantees and regression gates]({b}numbers/)
- [Method: how the palette is optimized]({b}method/)
- [Published sources]({b}science/)
- [Homepage with live dichromacy simulation]({b})

## Optional

- [llms-full.txt]({b}llms-full.txt): full documentation and all palette values
"""


def llms_full(variant):
    lines = ["# enot - full reference", ""]
    with open("docs/enot.en.md") as f:
        doc = f.read().strip()
    if doc.startswith("# "):  # we ship our own H1, the doc body suffices
        doc = doc.split("\n", 1)[1].strip()
    lines.append(doc)
    lines.append("\n## Palette values (sRGB hex; accents also as CIELAB LCh)\n")
    for mode in ("dark", "light"):
        lines.append(f"### {mode} theme\n")
        theme = variant[mode]
        for k in ROLE_KEYS:
            lch = theme.get("_lch", {}).get(k)
            suffix = (f" (L* {lch[0]}, C* {lch[1]}, h {lch[2]})"
                      if lch else "")
            lines.append(f"- {k}: {theme[k]}{suffix}")
        lines.append("")
        lines.append(f"### {mode} theme, ANSI 16\n")
        for n in ANSI_ORDER + ["br_" + n for n in ANSI_ORDER]:
            lines.append(f"- {n}: {variant['ansi'][mode][n]}")
        lines.append("")
    return "\n".join(lines) + "\n"


def main():
    from check import CHECKS
    variant = enot_variant()
    with open("colors.json") as f:
        spec = json.load(f)
    with open("ports/registry.json") as f:
        ports = json.load(f)
    acc, ansi = headline_numbers(spec)
    downloads = os.path.join(OUT, "downloads")
    # start clean: a renamed or removed artifact must not linger here
    # and get re-synced to the site by make deploy
    shutil.rmtree(downloads, ignore_errors=True)
    os.makedirs(downloads)
    with open(os.path.join(OUT, "site.json"), "w") as f:
        json.dump(bundle(variant, spec, CHECKS, ports), f,
                  separators=(",", ":"))
    with open(os.path.join(OUT, "llms.txt"), "w") as f:
        f.write(llms_txt(acc, ansi, ports["ports"]))
    with open(os.path.join(OUT, "llms-full.txt"), "w") as f:
        f.write(llms_full(variant))
    # downloads = every port artifact under its app directory + the spec
    for p in ports["ports"]:
        app_dir = os.path.join(downloads, p["app"])
        os.makedirs(app_dir, exist_ok=True)
        for o in p["outputs"]:
            shutil.copy(o["path"], app_dir)
    shutil.copy("colors.json", downloads)
    print(OUT)


if __name__ == "__main__":
    main()
